// <auto-generated />
using System;
using CatchARide.Data.Identity;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CatchARide.Data.Identity.Migrations {
    [DbContext(typeof(IdentityDbContext))]
    [Migration("20251108072820_InitialCreate")]
    partial class InitialCreate {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder) {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "citext");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CatchARide.Data.Identity.Models.AuditLog", b => {
                b.Property<Guid>("LogId")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid");

                b.Property<string>("Action")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("citext");

                b.Property<string>("IpAddress")
                    .HasMaxLength(45)
                    .HasColumnType("character varying(45)");

                b.Property<string>("Metadata")
                    .HasColumnType("jsonb");

                b.Property<string>("Outcome")
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnType("character varying(50)");

                b.Property<string>("ResourceId")
                    .HasMaxLength(100)
                    .HasColumnType("citext");

                b.Property<string>("ResourceType")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("citext");

                b.Property<DateTime>("Timestamp")
                    .HasColumnType("timestamp with time zone");

                b.Property<Guid>("UserId")
                    .HasColumnType("uuid");

                b.HasKey("LogId");

                b.HasIndex("Timestamp")
                    .HasDatabaseName("ix_audit_logs_timestamp");

                b.HasIndex("UserId")
                    .HasDatabaseName("ix_audit_logs_user_id");

                b.HasIndex("ResourceType", "ResourceId")
                    .HasDatabaseName("ix_audit_logs_resource_type_resource_id");

                b.ToTable("audit_logs", (string)null);
            });

            modelBuilder.Entity("CatchARide.Data.Identity.Models.Organization", b => {
                b.Property<Guid>("OrganizationId")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("timestamp with time zone");

                b.Property<bool>("IsActive")
                    .HasColumnType("boolean");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasMaxLength(255)
                    .HasColumnType("citext");

                b.HasKey("OrganizationId");

                b.HasIndex("IsActive")
                    .HasDatabaseName("ix_organizations_is_active");

                b.HasIndex("Name")
                    .HasDatabaseName("ix_organizations_name");

                b.ToTable("organizations", (string)null);
            });

            modelBuilder.Entity("CatchARide.Data.Identity.Models.Role", b => {
                b.Property<Guid>("RoleId")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("timestamp with time zone");

                b.Property<string>("Description")
                    .IsRequired()
                    .HasMaxLength(500)
                    .HasColumnType("text");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("citext");

                b.Property<string>("PhiAccessLevel")
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnType("character varying(50)");

                b.HasKey("RoleId");

                b.HasIndex("Name")
                    .IsUnique()
                    .HasDatabaseName("ix_roles_name");

                b.ToTable("roles", (string)null);
            });

            modelBuilder.Entity("CatchARide.Data.Identity.Models.User", b => {
                b.Property<Guid>("UserId")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("timestamp with time zone");

                b.Property<string>("Email")
                    .IsRequired()
                    .HasMaxLength(255)
                    .HasColumnType("citext");

                b.Property<bool>("IsActive")
                    .HasColumnType("boolean");

                b.Property<DateTime?>("LastLoginAt")
                    .HasColumnType("timestamp with time zone");

                b.Property<Guid>("OrganizationId")
                    .HasColumnType("uuid");

                b.Property<string>("Username")
                    .HasMaxLength(100)
                    .HasColumnType("citext");

                b.HasKey("UserId");

                b.HasIndex("Email")
                    .IsUnique()
                    .HasDatabaseName("ix_users_email");

                b.HasIndex("OrganizationId")
                    .HasDatabaseName("ix_users_organization_id");

                b.ToTable("users", (string)null);
            });

            modelBuilder.Entity("CatchARide.Data.Identity.Models.UserRole", b => {
                b.Property<Guid>("UserId")
                    .HasColumnType("uuid");

                b.Property<Guid>("RoleId")
                    .HasColumnType("uuid");

                b.Property<DateTime>("AssignedAt")
                    .HasColumnType("timestamp with time zone");

                b.Property<Guid?>("AssignedBy")
                    .HasColumnType("uuid");

                b.HasKey("UserId", "RoleId");

                b.HasIndex("RoleId")
                    .HasDatabaseName("ix_user_roles_role_id");

                b.HasIndex("UserId")
                    .HasDatabaseName("ix_user_roles_user_id");

                b.ToTable("user_roles", (string)null);
            });

            modelBuilder.Entity("CatchARide.Data.Identity.Models.AuditLog", b => {
                b.HasOne("CatchARide.Data.Identity.Models.User", "User")
                    .WithMany()
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();

                b.Navigation("User");
            });

            modelBuilder.Entity("CatchARide.Data.Identity.Models.User", b => {
                b.HasOne("CatchARide.Data.Identity.Models.Organization", "Organization")
                    .WithMany("Users")
                    .HasForeignKey("OrganizationId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();

                b.Navigation("Organization");
            });

            modelBuilder.Entity("CatchARide.Data.Identity.Models.UserRole", b => {
                b.HasOne("CatchARide.Data.Identity.Models.Role", "Role")
                    .WithMany("UserRoles")
                    .HasForeignKey("RoleId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.HasOne("CatchARide.Data.Identity.Models.User", "User")
                    .WithMany("UserRoles")
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Role");

                b.Navigation("User");
            });

            modelBuilder.Entity("CatchARide.Data.Identity.Models.Organization", b => {
                b.Navigation("Users");
            });

            modelBuilder.Entity("CatchARide.Data.Identity.Models.Role", b => {
                b.Navigation("UserRoles");
            });

            modelBuilder.Entity("CatchARide.Data.Identity.Models.User", b => {
                b.Navigation("UserRoles");
            });
#pragma warning restore 612, 618
        }
    }
}
