// <auto-generated />
using System;
using CatchARide.Data.Books;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CatchARide.Data.Books.Migrations {
    [DbContext(typeof(BooksDbContext))]
    [Migration("20251108050731_InitialCreate")]
    partial class InitialCreate {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder) {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "citext");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CatchARide.Data.Books.Models.Author", b => {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasMaxLength(150)
                    .HasColumnType("citext");

                b.HasKey("Id");

                b.HasIndex("Name")
                    .HasDatabaseName("ix_authors_name_trgm");

                b.ToTable("authors", (string)null);
            });

            modelBuilder.Entity("CatchARide.Data.Books.Models.Book", b => {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid");

                b.Property<string>("Title")
                    .IsRequired()
                    .HasMaxLength(200)
                    .HasColumnType("citext");

                b.Property<Guid?>("author_id")
                    .HasColumnType("uuid");

                b.HasKey("Id");

                b.HasIndex("Title")
                    .HasDatabaseName("ix_books_title_trgm");

                b.HasIndex("author_id");

                b.ToTable("books", (string)null);
            });

            modelBuilder.Entity("CatchARide.Data.Books.Models.Character", b => {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("integer");

                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                b.Property<string>("Name")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("citext");

                b.HasKey("Id");

                b.HasIndex("Name")
                    .HasDatabaseName("ix_characters_name_trgm");

                b.ToTable("characters", (string)null);
            });

            modelBuilder.Entity("book_characters", b => {
                b.Property<Guid>("book_id")
                    .HasColumnType("uuid");

                b.Property<int>("character_id")
                    .HasColumnType("integer");

                b.HasKey("book_id", "character_id");

                b.HasIndex("book_id")
                    .HasDatabaseName("ix_book_characters_book_id");

                b.HasIndex("character_id")
                    .HasDatabaseName("ix_book_characters_character_id");

                b.ToTable("book_characters", (string)null);
            });

            modelBuilder.Entity("CatchARide.Data.Books.Models.Book", b => {
                b.HasOne("CatchARide.Data.Books.Models.Author", "Author")
                    .WithMany("Books")
                    .HasForeignKey("author_id")
                    .OnDelete(DeleteBehavior.Cascade);

                b.Navigation("Author");
            });

            modelBuilder.Entity("book_characters", b => {
                b.HasOne("CatchARide.Data.Books.Models.Book", null)
                    .WithMany()
                    .HasForeignKey("book_id")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.HasOne("CatchARide.Data.Books.Models.Character", null)
                    .WithMany()
                    .HasForeignKey("character_id")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
            });

            modelBuilder.Entity("CatchARide.Data.Books.Models.Author", b => {
                b.Navigation("Books");
            });
#pragma warning restore 612, 618
        }
    }
}
